/**
 * DO NOT MODIFY THIS FILE DIRECTLY
 * Autogenerated file by the bin/create-env.js script
 * @generated 2020-01-20T21:58:25.014Z
 */
export const environment = {
	production: false,
	buildNumber: 'v0#' + Date.now(),
	assetCDNHost: 'https://cockpit.rheinklang-festival.ch',
	cockpitAPIURL: 'https://cockpit.rheinklang-festival.ch/api',
	cockpitAPIKey: '93ffad36b185594fc8a4c612064e8f',
	graphQLHostURL: 'https://cockpit.rheinklang-festival.ch/api/graphql/query?token=93ffad36b185594fc8a4c612064e8f',
	gtmId: 'UA-57645783-5',
	gcpKey: 'AIzaSyBqXCWSqYKNYCASQRZr06HDiRQF9BQljys',
	gcpStaticMapsSecret: 'd00duD8kGHzu7n5GKWruaYlFUWU',
	slackErrorHookURL: 'https://hooks.slack.com/services/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',
};


