/**
 * DO NOT MODIFY THIS FILE DIRECTLY
 * Autogenerated file by the bin/create-env.js script
 * @generated 2020-03-20T23:47:02.426Z
 */
export const environment = {
	production: false,
	buildNumber: '',
	assetCDNHost: '',
	cockpitAPIURL: '',
	cockpitAPIKey: '',
	graphQLHostURL: '',
	gtmId: '',
	gcpKey: '',
	gcpStaticMapsSecret: '',
	slackErrorHookURL: ''
};
import 'zone.js/dist/zone-error';
