export const GLOBAL_KEYWORDS = [
	'Rheinklang',
	'Rheinklang Festival',
	'Rheinklang Party',
	'Rheinklang Events',
	'Rheinklang Schweiz',
	'Rheinklang Widnau',
	'Events',
	'Schweiz',
	'Party',
	'Ostschweiz',
	'Partylabel',
	'Daydance',
	'Nightdance',
	'Festival',
	'Techno',
	'House',
	'Techhouse',
	'Deep House',
	'Dub House',
	'Rhema',
];
